//
//  Chapter2_numData.swift
//  DataTest
//
//  Created by ChoiYujin on 2023/03/28.
//

import Foundation


class Chapter2_2Data {
    
    static let dataList: [MainViewData] = [
        MainViewData(leftImage: "",
                     centerImage: "",
                     rightImage: "" ,
                     bgImage: "bg7",
                     peopleDirection: .none,
                     talkingPersonDirection: .none,
                     lineModels: LineModels(names: "", lines: "")),
        MainViewData(leftImage: "",
                     centerImage: "mal_annoyed",
                     rightImage: "" ,
                     bgImage: "bg7",
                     peopleDirection: .all,
                     talkingPersonDirection: .all,
                     lineModels: LineModels(names: "류포이", lines: "아니 어떻게 미션이 있는데, 솔루션을 생각 안할 수 있지?!?!")),
//        MainViewData(leftImage: "ron_annoyed",
//                     centerImage: "harry_scream",
//                     rightImage: "her_annoyed" ,
//                     bgImage: "bg7",
//                     peopleDirection: .all,
//                     talkingPersonDirection: .all,
//                     lineModels: LineModels(names: "해나포터, 산 위즐리, 화르미온느", lines: "거기 서 류포이!!")),
//        MainViewData(leftImage: "",
//                     centerImage: "mal_annoyed",
//                     rightImage: "" ,
//                     bgImage: "bg7",
//                     peopleDirection: .center,
//                     talkingPersonDirection: .center,
//                     lineModels: LineModels(names: "류포이", lines: "크윽, 두고보자!")),
        MainViewData(leftImage: "",
                     centerImage: "",
                     rightImage: "" ,
                     bgImage: "bg7",
                     peopleDirection: .none,
                     talkingPersonDirection: .none,
                     lineModels: LineModels(names: "내레이션", lines: "류포이의 함정에서 빠져나온 해나포터 일행은")),
        MainViewData(leftImage: "",
                     centerImage: "",
                     rightImage: "" ,
                     bgImage: "bg7",
                     peopleDirection: .none,
                     talkingPersonDirection: .none,
                     lineModels: LineModels(names: "내레이션", lines: "함정이 없는 왼쪽길로 걸어간다.")),
        MainViewData(leftImage: "",
                     centerImage: "",
                     rightImage: "" ,
                     bgImage: "bg8",
                     peopleDirection: .none,
                     talkingPersonDirection: .none,
                     lineModels: LineModels(names: "내레이션", lines: "한동안 걸어가던 해나포터 일행의 눈앞에 류포이가 다시 나타났다.", soundEffect: "mc1_sound_netfilx")),
//        MainViewData(leftImage: "ron_annoyed",
//                     centerImage: "harry_scream",
//                     rightImage: "her_annoyed" ,
//                     bgImage: "bg8",
//                     peopleDirection: .all,
//                     talkingPersonDirection: .all,
//                     lineModels: LineModels(names: "해나포터, 산 위즐리, 화르미온느", lines: "류포이 이번엔 꼭 잡고 말겠다!!!")),
        MainViewData(leftImage: "",
                     centerImage: "mal_smile",
                     rightImage: "" ,
                     bgImage: "bg8",
                     peopleDirection: .center,
                     talkingPersonDirection: .center,
                     lineModels: LineModels(names: "류포이", lines: "후후, 이번엔 그렇게 호락...")),
        MainViewData(leftImage: "ron_annoyed",
                     centerImage: "harry_scream",
                     rightImage: "her_annoyed" ,
                     bgImage: "bg8",
                     peopleDirection: .center,
                     talkingPersonDirection: .center,
                     lineModels: LineModels(names: "해나포터", lines: "입닥쳐 류포이!!")),
//        MainViewData(leftImage: "",
//                     centerImage: "mal_smile",
//                     rightImage: "" ,
//                     bgImage: "bg8",
//                     peopleDirection: .all,
//                     talkingPersonDirection: .all,
//                     lineModels: LineModels(names: "류포이", lines: "후후, 그렇게 말해도 이번엔....")),
//        MainViewData(leftImage: "ron_annoyed",
//                     centerImage: "",
//                     rightImage: "harry_scream" ,
//                     bgImage: "bg8",
//                     peopleDirection: .leftAndRight,
//                     talkingPersonDirection: .leftAndRight,
//                     lineModels: LineModels(names: "산 위즐리", lines: "입닥쳐 류포이!!")),
        MainViewData(leftImage: "",
                     centerImage: "mal_annoyed",
                     rightImage: "" ,
                     bgImage: "bg8",
                     peopleDirection: .center,
                     talkingPersonDirection: .center,
                     lineModels: LineModels(names: "류포이", lines: "아, 이거 너무한거 아니..")),
        MainViewData(leftImage: "ron_annoyed",
                     centerImage: "harry_scream",
                     rightImage: "her_annoyed" ,
                     bgImage: "bg8",
                     peopleDirection: .center,
                     talkingPersonDirection: .right,
                     lineModels: LineModels(names: "화르미온느", lines: "입닥쳐 류포이!")),
        MainViewData(leftImage: "",
                     centerImage: "mal_scream",
                     rightImage: "" ,
                     bgImage: "bg8",
                     peopleDirection: .center,
                     talkingPersonDirection: .center,
                     lineModels: LineModels(names: "류포이", lines: "으아아아아악!!!!")),
        MainViewData(leftImage: "",
                     centerImage: "",
                     rightImage: "" ,
                     bgImage: "bg8",
                     peopleDirection: .none,
                     talkingPersonDirection: .none,
                     lineModels: LineModels(names: "내레이션", lines: "이 정도면 너희가 나쁜놈이야..")),
        MainViewData(leftImage: "",
                     centerImage: "",
                     rightImage: "" ,
                     bgImage: "bg8",
                     peopleDirection: .none,
                     talkingPersonDirection: .none,
                     lineModels: LineModels(names: "내레이션", lines: "아무튼 류포이의 '소수는 버리고 가라~' 마법 함정이 발동되었다.")),
        MainViewData(leftImage: "ron_puzzled",
                     centerImage: "harry_smile",
                     rightImage: "her_smile" ,
                     bgImage: "bg8",
                     peopleDirection: .all,
                     talkingPersonDirection: .center,
                     lineModels: LineModels(names: "해나포터", lines: "그래~ 모두의 의견을 챙길 순 없어~~")),
        MainViewData(leftImage: "ron_puzzled",
                     centerImage: "harry_smile",
                     rightImage: "her_smile" ,
                     bgImage: "bg8",
                     peopleDirection: .all,
                     talkingPersonDirection: .left,
                     lineModels: LineModels(names: "산 위즐리", lines: "뭐야 너네들 왜 그래?")),
        MainViewData(leftImage: "ron_puzzled",
                     centerImage: "harry_smile",
                     rightImage: "her_annoyed",
                     bgImage: "bg8",
                     peopleDirection: .all,
                     talkingPersonDirection: .right,
                     lineModels: LineModels(names: "화르미온느", lines: "입닥쳐 산!")),
        MainViewData(leftImage: "ron_puzzled",
                     centerImage: "harry_smile",
                     rightImage: "her_annoyed" ,
                     bgImage: "bg8",
                     peopleDirection: .all,
                     talkingPersonDirection: .left,
                     lineModels: LineModels(names: "산 위즐리", lines: "....? 미쳤어?")),
        MainViewData(leftImage: "",
                     centerImage: "dumb_smile",
                     rightImage: "" ,
                     bgImage: "bg8",
                     peopleDirection: .all,
                     talkingPersonDirection: .all,
                     lineModels: LineModels(names: "내레이션", lines: "이때 멀리서 다가오는 우리의 사야도어!!")),
        MainViewData(leftImage: "",
                     centerImage: "dumb_smile",
                     rightImage: "" ,
                     bgImage: "bg8",
                     peopleDirection: .center,
                     talkingPersonDirection: .center,
                     lineModels: LineModels(names: "사야도어", lines: "호호~ 여러분 잘 돼가고 계신가요~", soundEffect: "mc1_sound_hoho")),
//        MainViewData(leftImage: "ron_puzzled",
//                     centerImage: "harry_puzzled",
//                     rightImage: "her_puzzled" ,
//                     bgImage: "bg8",
//                     peopleDirection: .all,
//                     talkingPersonDirection: .all,
//                     lineModels: LineModels(names: "해나포터, 산 위즐리, 화르미온느", lines: "교수님?")),
//        MainViewData(leftImage: "",
//                     centerImage: "dumb_smile",
//                     rightImage: "" ,
//                     bgImage: "bg8",
//                     peopleDirection: .center,
//                     talkingPersonDirection: .center,
//                     lineModels: LineModels(names: "사야도어", lines: "호호호호~")),
        MainViewData(leftImage: "ron_annoyed",
                     centerImage: "harry_smile",
                     rightImage: "her_smile" ,
                     bgImage: "bg8",
                     peopleDirection: .all,
                     talkingPersonDirection: .left,
                     lineModels: LineModels(names: "산 위즐리", lines: "교수님 도와주세요 ㅠ 아무도 제 말을 들어주지 않아요 ,, ")),
//        MainViewData(leftImage: "",
//                     centerImage: "dumb_smile",
//                     rightImage: "" ,
//                     bgImage: "bg8",
//                     peopleDirection: .center,
//                     talkingPersonDirection: .center,
//                     lineModels: LineModels(names: "사야도어", lines: "여러분 학생 장학금 신청서류 불태워 버리겠습니다.")),
//        MainViewData(leftImage: "ron_annoyed",
//                     centerImage: "harry_scream",
//                     rightImage: "her_annoyed" ,
//                     bgImage: "bg8",
//                     peopleDirection: .all,
//                     talkingPersonDirection: .all,
//                     lineModels: LineModels(names: "해나포터, 산 위즐리, 화르미온느", lines: "죽음을 각오하겠습니다! 시켜만 주십시오!")),
        MainViewData(leftImage: "",
                     centerImage: "dumb_smile",
                     rightImage: "" ,
                     bgImage: "bg8",
                     peopleDirection: .center,
                     talkingPersonDirection: .center,
                     lineModels: LineModels(names: "사야도어", lines: "여러분~ 소수의 의견도 버려지면 안돼요~ 그치만 이번에도 제 말이 정답은 아니에요 ㅎㅎ"))
    ]
    
}
