//
//  Chapter4_1Data.swift
//  DataTest
//
//  Created by ChoiYujin on 2023/03/28.
//

import Foundation

class Chapter4_1Data {
    
   static let dataList: [MainViewData] = [
    MainViewData(leftImage: "",
                 centerImage: "",
                 rightImage: "" ,
                 bgImage: "bg15",
                 peopleDirection: .none,
                 talkingPersonDirection: .none,
                 lineModels: LineModels(names: "", lines: "")),
        MainViewData(leftImage: "", // 왼쪽에 들어갈 사람 이미지파일명 ex) harry_smile.png면 harry_smile
                     centerImage: "mcg_serious", // 중앙에 들어갈 사람 이미지파일명
                     rightImage: "" , // 오른쪽에 들어갈 사람 이미지파일명
                     bgImage: "bg15", // 배경에 들어갈 사람 이미지파일명
                     peopleDirection: .center, // 화면에 나올 전체 사람 위치 (말 안하는 사람은 검은색으로 자리는 차지하도록)
                     talkingPersonDirection: .center, // 현재 말하는 사람 위치 (말하는 사람은 밝게 만들어주도록)
                     lineModels: LineModels(names: "맥고나걸", lines: "여러분 주목하세요.", soundEffect: "mc1_sound_jong")), // 말하는 사람 이름, 대사, 효과음 파일명 확장자 빼고
        MainViewData(leftImage: "npc",
                     centerImage: "npc",
                     rightImage: "npc" ,
                     bgImage: "bg15",
                     peopleDirection: .all,
                     talkingPersonDirection: .all,
                     lineModels: LineModels(names: "호그와트 학생들", lines: "웅성 웅성 웅성 웅성")),
        MainViewData(leftImage: "", // 여긴 일부러 공백으로 놔두기
                     centerImage: "mcg_smile",
                     rightImage: "appleinsied" ,
                     bgImage: "bg15",
                     peopleDirection: .all,
                     talkingPersonDirection: .all,
                     lineModels: LineModels(names: "맥고나걸", lines: "해리포터,헤르미온느,론위즐리가 되찾아온마법서'애플 인사이드'입니다.")),
        MainViewData(leftImage: "",
                     centerImage: "dumb_smile",
                     rightImage: "" ,
                     bgImage: "bg15",
                     peopleDirection: .center,
                     talkingPersonDirection: .center,
                     lineModels: LineModels(names: "덤블도어", lines: "우리는 무한한 에너지를 품고 있는 '애플 인사이드'가 모두에게 에너지를 나눠주며,")),
        MainViewData(leftImage: "",
                     centerImage: "dumb_smile",
                     rightImage: "" ,
                     bgImage: "bg15",
                     peopleDirection: .center,
                     talkingPersonDirection: .center,
                     lineModels: LineModels(names: "덤블도어", lines: "우리 모두가 충만한 원동력을 가질수 있도록")),
        MainViewData(leftImage: "",
                     centerImage: "dumb_smile",
                     rightImage: "" ,
                     bgImage: "bg15",
                     peopleDirection: .center,
                     talkingPersonDirection: .center,
                     lineModels: LineModels(names: "덤블도어", lines: "호그와트 메인 로비에 걸어두기로 했습니다!!")),
        MainViewData(leftImage: "npc",
                     centerImage: "npc",
                     rightImage: "npc" ,
                     bgImage: "bg15",
                     peopleDirection: .all,
                     talkingPersonDirection: .all,
                     lineModels: LineModels(names: "호그와트 학생들", lines: "우와와와~~~ 우와와와~~~~~", soundEffect: "mc1_sound_hamsung")),
        MainViewData(leftImage: "ron_smile",
                     centerImage: "harry_smile",
                     rightImage: "her_smile" ,
                     bgImage: "bg15",
                     peopleDirection: .all,
                     talkingPersonDirection: .all,
                     lineModels: LineModels(names: "해리포터, 론위즐리, 헤르미온느", lines: "우리는 최고의 팀이야!!")),
        MainViewData(leftImage: "",
                     centerImage: "ron_suprised",
                     rightImage: "" ,
                     bgImage: "bg15",
                     peopleDirection: .center,
                     talkingPersonDirection: .center,
                     lineModels: LineModels(names: "론위즐리", lines: "어? 저기 말포이 잖아??")),
        MainViewData(leftImage: "",
                     centerImage: "",
                     rightImage: "mal_mung" ,
                     bgImage: "bg16",
                     peopleDirection: .right,
                     talkingPersonDirection: .right,
                     lineModels: LineModels(names: "나레이션", lines: "말포이는 이번 사건 반성의 의미로, 교과서 'HIG' 100번 받아쓰기 숙제를 받았다.")),
    MainViewData(leftImage: "",
                 centerImage: "",
                 rightImage: "mal_mung" ,
                 bgImage: "bg16",
                 peopleDirection: .right,
                 talkingPersonDirection: .right,
                 lineModels: LineModels(names: "나레이션", lines: "교과서 'HIG' 100번 받아쓰기 숙제를 받았다.")),
        MainViewData(leftImage: "",
                     centerImage: "mal_mung",
                     rightImage: "" ,
                     bgImage: "bg16",
                     peopleDirection: .center,
                     talkingPersonDirection: .center,
                     lineModels: LineModels(names: "말포이", lines: "터벅 터벅 터벅")),
        MainViewData(leftImage: "",
                     centerImage: "harry_smile",
                     rightImage: "" ,
                     bgImage: "bg16",
                     peopleDirection: .center,
                     talkingPersonDirection: .center,
                     lineModels: LineModels(names: "해리포터", lines: "말포이!!")),
        MainViewData(leftImage: "",
                     centerImage: "mal_suprised",
                     rightImage: "" ,
                     bgImage: "bg16",
                     peopleDirection: .center,
                     talkingPersonDirection: .center,
                     lineModels: LineModels(names: "말포이", lines: "해....해리!! 미.. 미안해..")),
//        MainViewData(leftImage: "",
//                     centerImage: "mal_sad",
//                     rightImage: "" ,
//                     bgImage: "bg16",
//                     peopleDirection: .center,
//                     talkingPersonDirection: .center,
//                     lineModels: LineModels(names: "말포이", lines: "미..미안해..해리..ㅠㅠ")),
        MainViewData(leftImage: "",
                     centerImage: "harry_smile",
                     rightImage: "" ,
                     bgImage: "bg16",
                     peopleDirection: .center,
                     talkingPersonDirection: .center,
                     lineModels: LineModels(names: "해리포터", lines: "말포이! 우리.. 좋은 친구가 될 수 있지 않을까??")),
        MainViewData(leftImage: "",
                     centerImage: "mal_suprised",
                     rightImage: "" ,
                     bgImage: "bg16",
                     peopleDirection: .center,
                     talkingPersonDirection: .center,
                     lineModels: LineModels(names: "말포이", lines: "정말? 진짜 그럴 수 있을까?")),
        MainViewData(leftImage: "",
                     centerImage: "harry_smile",
                     rightImage: "" ,
                     bgImage: "bg16",
                     peopleDirection: .center,
                     talkingPersonDirection: .center,
                     lineModels: LineModels(names: "해리포터", lines: "그럼!! 우리는 이미 친구야!!")),
        
        MainViewData(leftImage: "",
                     centerImage: "mal_smile",
                     rightImage: "" ,
                     bgImage: "bg16",
                     peopleDirection: .center,
                     talkingPersonDirection: .center,
                     lineModels: LineModels(names: "말포이", lines: "그럼 우리 HIG 받아쓰기 같이하자!!")),
        MainViewData(leftImage: "",
                     centerImage: "harry_annoyed",
                     rightImage: "" ,
                     bgImage: "bg16",
                     peopleDirection: .all,
                     talkingPersonDirection: .all,
                     lineModels: LineModels(names: "해리포터", lines: "입닥쳐 말포이!!",soundEffect: "mc1_sound_netfilx"))
    ]
}
