//
//  Chapter2_numData.swift
//  DataTest
//
//  Created by ChoiYujin on 2023/03/28.
//

import Foundation


class Chapter2_2Data {
    
    static let dataList: [MainViewData] = [
        MainViewData(leftImage: "",
                     centerImage: "mal_annoyed",
                     rightImage: "" ,
                     bgImage: "bg7",
                     peopleDirection: .all,
                     talkingPersonDirection: .all,
                     lineModels: LineModels(names: "말포이", lines: "아니 어떻게 미션이 있는데, 솔루션을 생각 안할수 있지?!?!")),
        MainViewData(leftImage: "ron_scream",
                     centerImage: "harry_scream",
                     rightImage: "her_scream" ,
                     bgImage: "bg7",
                     peopleDirection: .all,
                     talkingPersonDirection: .all,
                     lineModels: LineModels(names: "해리포터, 론위즐리, 헤르미온느", lines: "거기서 말포이!!")),
        MainViewData(leftImage: "",
                     centerImage: "mal_annoyed",
                     rightImage: "" ,
                     bgImage: "bg7",
                     peopleDirection: .center,
                     talkingPersonDirection: .center,
                     lineModels: LineModels(names: "말포이", lines: "크윽, 두고보자!")),
        MainViewData(leftImage: "",
                     centerImage: "",
                     rightImage: "" ,
                     bgImage: "bg7",
                     peopleDirection: .none,
                     talkingPersonDirection: .none,
                     lineModels: LineModels(names: "내래이션", lines: "말포이의 함정에서 빠져나온 해리포터 일행은")),
        MainViewData(leftImage: "",
                     centerImage: "",
                     rightImage: "" ,
                     bgImage: "bg7",
                     peopleDirection: .none,
                     talkingPersonDirection: .none,
                     lineModels: LineModels(names: "내래이션", lines: "이전 갈림길로 돌아가 함정이 없는 왼쪽길로 걸어간다.")),
        MainViewData(leftImage: "",
                     centerImage: "",
                     rightImage: "" ,
                     bgImage: "bg8",
                     peopleDirection: .none,
                     talkingPersonDirection: .none,
                     lineModels: LineModels(names: "내래이션", lines: "한동안 걸어가던 해리포터 일행의 눈앞에 말포이가 다시 나타났다.", soundEffect: "mc1_sound_netfilx")),
        MainViewData(leftImage: "ron_scream",
                     centerImage: "harry_scream",
                     rightImage: "her_scream" ,
                     bgImage: "bg8",
                     peopleDirection: .all,
                     talkingPersonDirection: .all,
                     lineModels: LineModels(names: "해리포터, 론위즐리, 헤르미온느", lines: "말포이 이번엔 꼭 잡고 말겠다!!!")),
        MainViewData(leftImage: "",
                     centerImage: "mal_smile",
                     rightImage: "" ,
                     bgImage: "bg8",
                     peopleDirection: .center,
                     talkingPersonDirection: .center,
                     lineModels: LineModels(names: "말포이", lines: "후후, 이번엔 그렇게 호락...")),
        MainViewData(leftImage: "ron_scream",
                     centerImage: "harry_scream",
                     rightImage: "her_scream" ,
                     bgImage: "bg8",
                     peopleDirection: .center,
                     talkingPersonDirection: .center,
                     lineModels: LineModels(names: "해리포터", lines: "입닥쳐 말포이!!")),
        MainViewData(leftImage: "",
                     centerImage: "mal_smile",
                     rightImage: "" ,
                     bgImage: "bg8",
                     peopleDirection: .all,
                     talkingPersonDirection: .all,
                     lineModels: LineModels(names: "말포이", lines: "후후, 그렇게 말해도 이번엔....")),
        MainViewData(leftImage: "ron_scream",
                     centerImage: "",
                     rightImage: "harry_scream" ,
                     bgImage: "bg8",
                     peopleDirection: .leftAndRight,
                     talkingPersonDirection: .leftAndRight,
                     lineModels: LineModels(names: "론위즐리", lines: "입닥쳐 말포이!!")),
        MainViewData(leftImage: "",
                     centerImage: "mal_annoyed",
                     rightImage: "" ,
                     bgImage: "bg8",
                     peopleDirection: .center,
                     talkingPersonDirection: .center,
                     lineModels: LineModels(names: "말포이", lines: "아, 이거 너무한거 아니..")),
        MainViewData(leftImage: "ron_scream",
                     centerImage: "harry_scream",
                     rightImage: "her_scream" ,
                     bgImage: "bg8",
                     peopleDirection: .center,
                     talkingPersonDirection: .center,
                     lineModels: LineModels(names: "헤르미온느", lines: "입닥쳐 말포이!")),
        MainViewData(leftImage: "",
                     centerImage: "mal_angry",
                     rightImage: "" ,
                     bgImage: "bg8",
                     peopleDirection: .center,
                     talkingPersonDirection: .center,
                     lineModels: LineModels(names: "말포이", lines: "으아아아아악!!!!")),
        MainViewData(leftImage: "",
                     centerImage: "",
                     rightImage: "" ,
                     bgImage: "bg8",
                     peopleDirection: .none,
                     talkingPersonDirection: .none,
                     lineModels: LineModels(names: "내레이션", lines: "이 정도면 너희가 나쁜놈이야..")),
        MainViewData(leftImage: "",
                     centerImage: "",
                     rightImage: "" ,
                     bgImage: "bg8",
                     peopleDirection: .none,
                     talkingPersonDirection: .none,
                     lineModels: LineModels(names: "내레이션", lines: "아무튼 말포이의 '소수는 버리고 가라~' 마법 함정이 발동되었다.")),
        MainViewData(leftImage: "ron_puzzled",
                     centerImage: "harry_puzzled",
                     rightImage: "her_puzzled" ,
                     bgImage: "bg8",
                     peopleDirection: .all,
                     talkingPersonDirection: .left,
                     lineModels: LineModels(names: "론위즐리", lines: "응? 뭐지 아무렇지 않은데?")),
        MainViewData(leftImage: "ron_puzzled",
                     centerImage: "harry_annoyed",
                     rightImage: "her_annoyed" ,
                     bgImage: "bg8",
                     peopleDirection: .all,
                     talkingPersonDirection: .center,
                     lineModels: LineModels(names: "해리포터", lines: "빨간머리는 빠져~")),
        MainViewData(leftImage: "ron_puzzled",
                     centerImage: "harry_annoyed",
                     rightImage: "her_annoyed",
                     bgImage: "bg8",
                     peopleDirection: .all,
                     talkingPersonDirection: .left,
                     lineModels: LineModels(names: "론위즐리", lines: "왜그래 해리??")),
        MainViewData(leftImage: "ron_puzzled",
                     centerImage: "harry_annoyed",
                     rightImage: "her_annoyed",
                     bgImage: "bg8",
                     peopleDirection: .all,
                     talkingPersonDirection: .right,
                     lineModels: LineModels(names: "헤르미온느", lines: "입닥쳐 론!")),
        MainViewData(leftImage: "ron_angry",
                     centerImage: "harry_annoyed",
                     rightImage: "her_annoyed" ,
                     bgImage: "bg8",
                     peopleDirection: .all,
                     talkingPersonDirection: .left,
                     lineModels: LineModels(names: "론위즐리", lines: "우쒸!! 화가난다!!")),
        MainViewData(leftImage: "",
                     centerImage: "dumb_smile",
                     rightImage: "" ,
                     bgImage: "bg8",
                     peopleDirection: .all,
                     talkingPersonDirection: .all,
                     lineModels: LineModels(names: "내레이션", lines: "이때 멀리서 다가오는 우리의 덤블도어!!")),
        MainViewData(leftImage: "",
                     centerImage: "dumb_smile",
                     rightImage: "" ,
                     bgImage: "bg8",
                     peopleDirection: .center,
                     talkingPersonDirection: .center,
                     lineModels: LineModels(names: "덤블도어", lines: "호호호호", soundEffect: "mc1_sound_hoho")),
        MainViewData(leftImage: "ron_puzzled",
                     centerImage: "harry_puzzled",
                     rightImage: "her_puzzled" ,
                     bgImage: "bg8",
                     peopleDirection: .all,
                     talkingPersonDirection: .all,
                     lineModels: LineModels(names: "해리포터, 론위즐리, 헤르미온느", lines: "교수님?")),
        MainViewData(leftImage: "",
                     centerImage: "dumb_smile",
                     rightImage: "" ,
                     bgImage: "bg8",
                     peopleDirection: .center,
                     talkingPersonDirection: .center,
                     lineModels: LineModels(names: "덤블도어", lines: "호호호호~")),
        MainViewData(leftImage: "ron_annoyed",
                     centerImage: "harry_annoyed",
                     rightImage: "her_puzzled" ,
                     bgImage: "bg8",
                     peopleDirection: .all,
                     talkingPersonDirection: .all,
                     lineModels: LineModels(names: "해리포터, 론위즐리, 헤르미온느", lines: "계속 오실거면 직접와서 해결해도 되잖아요!!")),
        MainViewData(leftImage: "",
                     centerImage: "dumb_smile",
                     rightImage: "" ,
                     bgImage: "bg8",
                     peopleDirection: .center,
                     talkingPersonDirection: .center,
                     lineModels: LineModels(names: "덤블도어", lines: "여러분 학생 장학금 신청서류 불태워 버리겠습니다.")),
        MainViewData(leftImage: "ron_scream",
                     centerImage: "harry_scream",
                     rightImage: "her_scream" ,
                     bgImage: "bg8",
                     peopleDirection: .all,
                     talkingPersonDirection: .all,
                     lineModels: LineModels(names: "해리포터, 론위즐리, 헤르미온느", lines: "죽음을 각오하겠습니다! 시켜만 주십시오!")),
        MainViewData(leftImage: "",
                     centerImage: "dumb_smile",
                     rightImage: "" ,
                     bgImage: "bg8",
                     peopleDirection: .center,
                     talkingPersonDirection: .center,
                     lineModels: LineModels(names: "덤블도어", lines: "여러분~ 모두와 함께 나아가야해요~"))
    ]
    
}
