//
//  Chapter3Data.swift
//  DataTest
//
//  Created by ChoiYujin on 2023/03/28.
//

import Foundation

class Chapter3_1Data {
    static let dataList: [MainViewData] = [
        MainViewData(leftImage: "",
                     centerImage: "",
                     rightImage: "" ,
                     bgImage: "bg11",
                     peopleDirection: .none,
                     talkingPersonDirection: .none,
                     lineModels: LineModels(names: "", lines: "")),
        MainViewData(leftImage: "ron_painful",
                     centerImage: "harry_painful",
                     rightImage: "her_painful" ,
                     bgImage: "bg11",
                     peopleDirection: .all,
                     talkingPersonDirection: .left,
                     lineModels: LineModels(names: "산 위즐리", lines: "헉헉헉, 어디까지 가야하는거야..",soundEffect: "mc1_sound_walk")),
        MainViewData(leftImage: "ron_painful",
                     centerImage: "harry_painful",
                     rightImage: "her_painful" ,
                     bgImage: "bg11",
                     peopleDirection: .all,
                     talkingPersonDirection: .left,
                     lineModels: LineModels(names: "해나포터", lines: "배고파....")),
        MainViewData(leftImage: "ron_painful",
                     centerImage: "harry_painful",
                     rightImage: "her_painful" ,
                     bgImage: "bg11",
                     peopleDirection: .all,
                     talkingPersonDirection: .right,
                     lineModels: LineModels(names: "해르미온느", lines: "다리도 아프고.. 으아! 더 이상은 못가!! 나 안해!!")),
//        MainViewData(leftImage: "ron_angry",
//                     centerImage: "harry_painful",
//                     rightImage: "her_painful" ,
//                     bgImage: "bg11",
//                     peopleDirection: .all,
//                     talkingPersonDirection: .left,
//                     lineModels: LineModels(names: "산 위즐리", lines: "너만 힘들어? 나도 힘들다고!!")),
//        MainViewData(leftImage: "ron_painful",
//                     centerImage: "harry_annoyed",
//                     rightImage: "her_painful" ,
//                     bgImage: "bg11",
//                     peopleDirection: .all,
//                     talkingPersonDirection: .right,
//                     lineModels: LineModels(names: "해나포터", lines: "아 몰랑. 될대로 되라~")),
//        MainViewData(leftImage: "ron_annoyed",
//                     centerImage: "harry_annoyed",
//                     rightImage: "her_annoyed" ,
//                     bgImage: "bg11",
//                     peopleDirection: .all,
//                     talkingPersonDirection: .all,
//                     lineModels: LineModels(names: "해나포터, 산 위즐리, 화르미온느", lines: "투덜 투덜 투덜...")),
        MainViewData(leftImage: "ron_annoyed",
                     centerImage: "harry_annoyed",
                     rightImage: "her_annoyed" ,
                     bgImage: "bg11",
                     peopleDirection: .all,
                     talkingPersonDirection: .none,
                     lineModels: LineModels(names: "내레이션", lines: "팀 와해 위기의 해나포터 일행!! 그들앞에 누군가가 다가온다.")),
        MainViewData(leftImage: "",
                     centerImage: "hag_smile",
                     rightImage: "" ,
                     bgImage: "bg11",
                     peopleDirection: .center,
                     talkingPersonDirection: .center,
                     lineModels: LineModels(names: "유그리드", lines: "무홧홧홧!! 여기 있었구나 너희들!!", soundEffect: "mc1_sound_hothot")),
        MainViewData(leftImage: "ron_surprised",
                     centerImage: "harry_surprised",
                     rightImage: "her_surprised" ,
                     bgImage: "bg11",
                     peopleDirection: .all,
                     talkingPersonDirection: .all,
                     lineModels: LineModels(names: "해나포터, 산 위즐리, 해르미온느", lines: "유그리드!!")),
        MainViewData(leftImage: "",
                     centerImage: "hag_smile",
                     rightImage: "" ,
                     bgImage: "bg11",
                     peopleDirection: .center,
                     talkingPersonDirection: .center,
                     lineModels: LineModels(names: "유그리드", lines: "무홧홧홧!! 너희들이 힘들줄 알고 내가 달려왔다. 이것 먹고 힘들 내거라!!", soundEffect: "mc1_sound_hothot")),
        MainViewData(leftImage: "ron_surprised",
                     centerImage: "harry_surprised",
                     rightImage: "her_surprised" ,
                     bgImage: "bg11",
                     peopleDirection: .all,
                     talkingPersonDirection: .all,
                     lineModels: LineModels(names: "해나포터, 산 위즐리, 화르미온느", lines: "아니 이것은!! 호그와트의")),
//        MainViewData(leftImage: "ron_surprised",
//                     centerImage: "harry_surprised",
//                     rightImage: "her_surprised" ,
//                     bgImage: "bg11",
//                     peopleDirection: .left,
//                     talkingPersonDirection: .left,
//                     lineModels: LineModels(names: "산 위즐리", lines: "특!")),
        MainViewData(leftImage: "ron_surprised",
                     centerImage: "harry_surprised",
                     rightImage: "her_surprised" ,
                     bgImage: "bg11",
                     peopleDirection: .leftAndRight,
                     talkingPersonDirection: .leftAndRight,
                     lineModels: LineModels(names: "화르미온느", lines: "특!산!품!!!!")),
//        MainViewData(leftImage: "ron_surprised",
//                     centerImage: "harry_surprised",
//                     rightImage: "her_surprised" ,
//                     bgImage: "bg11",
//                     peopleDirection: .all,
//                     talkingPersonDirection: .all,
//                     lineModels: LineModels(names: "해나포터", lines: "품!")),
        MainViewData(leftImage: "",
                     centerImage: "agu",
                     rightImage: "" ,
                     bgImage: "bg11",
                     peopleDirection: .all,
                     talkingPersonDirection: .all,
                     lineModels: LineModels(names: "해나포터, 산 위즐리, 화르미온느", lines: "아구수육!!!", soundEffect: "mc1_sound_netfilx")),
//        MainViewData(leftImage: "",
//                     centerImage: "agu",
//                     rightImage: "" ,
//                     bgImage: "bg11",
//                     peopleDirection: .center,
//                     talkingPersonDirection: .center,
//                     lineModels: LineModels(names: "아구수육", lines: "두둥!!")),
        MainViewData(leftImage: "",
                     centerImage: "agu",
                     rightImage: "" ,
                     bgImage: "bg11",
                     peopleDirection: .center,
                     talkingPersonDirection: .center,
                     lineModels: LineModels(names: "내레이션", lines: "해나포터 일행은 눈이 돌아가서 아구수육을 걸신 들린듯이 먹어치운다.")),
        MainViewData(leftImage: "ron_fire",
                     centerImage: "harry_fire",
                     rightImage: "her_fire" ,
                     bgImage: "bg11",
                     peopleDirection: .all,
                     talkingPersonDirection: .center,
                     lineModels: LineModels(names: "해나포터", lines: "우오오오!! 힘이 넘쳐흐른다!!")),
        MainViewData(leftImage: "ron_fire",
                     centerImage: "harry_fire",
                     rightImage: "her_fire" ,
                     bgImage: "bg11",
                     peopleDirection: .all,
                     talkingPersonDirection: .leftAndRight,
                     lineModels: LineModels(names: "화르미온느", lines: "우리는 하나!!!!!!")),
//        MainViewData(leftImage: "ron_fire",
//                     centerImage: "harry_fire",
//                     rightImage: "her_fire" ,
//                     bgImage: "bg11",
//                     peopleDirection: .all,
//                     talkingPersonDirection: .all,
//                     lineModels: LineModels(names: "산 위즐리", lines: "함께 위기를 헤쳐나간다!!")),
//        MainViewData(leftImage: "",
//                     centerImage: "hag_smile",
//                     rightImage: "" ,
//                     bgImage: "bg11",
//                     peopleDirection: .center,
//                     talkingPersonDirection: .center,
//                     lineModels: LineModels(names: "유그리드", lines: "무홧홧홧홧!!!!", soundEffect: "mc1_sound_hothot")),
        MainViewData(leftImage: "ron_surprised",
                     centerImage: "harry_surprised",
                     rightImage: "her_surprised" ,
                     bgImage: "bg12",
                     peopleDirection: .all,
                     talkingPersonDirection: .none,
                     lineModels: LineModels(names: "내레이션", lines: "드디어 '씨퐈'의 마지막에 도착한 해나포터 일행.",soundEffect: "mc1_sound_netfilx")),
        MainViewData(leftImage: "ron_surprised",
                     centerImage: "harry_surprised",
                     rightImage: "her_surprised" ,
                     bgImage: "bg12",
                     peopleDirection: .all,
                     talkingPersonDirection: .none,
                     lineModels: LineModels(names: "내레이션", lines: "그들을 기다리고 있는 류포이",soundEffect: "mc1_sound_netfilx")),
        MainViewData(leftImage: "ron_surprised",
                     centerImage: "harry_surprised",
                     rightImage: "her_surprised" ,
                     bgImage: "bg12",
                     peopleDirection: .all,
                     talkingPersonDirection: .none,
                     lineModels: LineModels(names: "내레이션", lines: "류포이는 금지된 마법서를 펼치며 외친다.")),
        MainViewData(leftImage: "",
                     centerImage: "mal_scream",
                     rightImage: "" ,
                     bgImage: "bg12",
                     peopleDirection: .center,
                     talkingPersonDirection: .center,
                     lineModels: LineModels(names: "류포이", lines: "애플 인사이드!!")),
//        MainViewData(leftImage: "",
//                     centerImage: "mal_fire",
//                     rightImage: "" ,
//                     bgImage: "bg12",
//                     peopleDirection: .center,
//                     talkingPersonDirection: .center,
//                     lineModels: LineModels(names: "류포이", lines: "우오오오오오!!")),  // 포스트잇 사진을 양옆에?
        MainViewData(leftImage: "",
                     centerImage: "mal_fire",
                     rightImage: "" ,
                     bgImage: "bg12",
                     peopleDirection: .all,
                     talkingPersonDirection: .all,
                     lineModels: LineModels(names: "내레이션", lines: "수많은 마법사들의 에너지가 담긴 포스트잇으로! ")),  // 포스트잇 사진을 양옆에?
        MainViewData(leftImage: "",
                     centerImage: "mal_fire",
                     rightImage: "" ,
                     bgImage: "bg12",
                     peopleDirection: .all,
                     talkingPersonDirection: .all,
                     lineModels: LineModels(names: "내레이션", lines: "'엠씨완 류포이로'로 변신한다.")),  // 포스트잇 사진을 양옆에?
//        MainViewData(leftImage: "",
//                     centerImage: "MC1mal_angry",
//                     rightImage: "" ,
//                     bgImage: "bg12",
//                     peopleDirection: .center,
//                     talkingPersonDirection: .center,
//                     lineModels: LineModels(names: "내레이션", lines: "콰앙!! 콰앙!! 콰앙!!", soundEffect: "mc!_sound_boom")),
        MainViewData(leftImage: "",
                     centerImage: "MC1mal_angry",
                     rightImage: "" ,
                     bgImage: "bg12",
                     peopleDirection: .center,
                     talkingPersonDirection: .center,
                     lineModels: LineModels(names: "엠씨완 류포이", lines: "이것으로 너희는 끝이다!!")),
        MainViewData(leftImage: "",
                     centerImage: "MC1mal_smile",
                     rightImage: "" ,
                     bgImage: "bg12",
                     peopleDirection: .center,
                     talkingPersonDirection: .center,
                     lineModels: LineModels(names: "엠씨완 류포이", lines: "[마법주문] 눈감아봐. 깜깜하지? 그게 네 미래야!!")),
        MainViewData(leftImage: "",
                     centerImage: "",
                     rightImage: "" ,
                     bgImage: "bg12",
                     peopleDirection: .none,
                     talkingPersonDirection: .none,
                     lineModels: LineModels(names: "내레이션", lines: "류포이의 마법공격을 받은 해나포터 일행은")), // 어두워지는애니메이션
        MainViewData(leftImage: "",
                     centerImage: "",
                     rightImage: "" ,
                     bgImage: "bg12",
                     peopleDirection: .none,
                     talkingPersonDirection: .none,
                     lineModels: LineModels(names: "내레이션", lines: "아무것도 안보이는 상황에 절망한다.")) // 어두워지는애니메이션
    ]
    
}
